### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by AlienFreek** [Percdye7/destiny2solo-PS#1]
Doesn't seem to work for me anymore. Probably changed something with Witch Queen.

**Comment by Percdye7** [comment]
Hey, what exactly is not working?

Is the game crashing or are you seeing other players?

**Comment by AlienFreek** [comment]
A few months late, I was just being stupid. Just replying to close the issue. The app works perfectly, my firewall settings were conflicting with the rules the app makes.
